### ISSUE TITLE
有关模型端到端训练

### ISSUE THREAD

**Issue by NanCheng2001** [zsl-whu/csc-mvs#1]
您好，注意到您的模型使用了两个聚类方法。在整个网络中，您的网络是端到端可训练的嘛？我的理解是，您的聚类方法是无法端到端学习的，所以整个网络也不是端到端的。可以这样理解吗？

**Comment by zsl-whu** [comment]
您好，我的网络均以MVSNet等系列网络为基础，属于可端到端训练的网络。

-----原始邮件-----
发件人:NanCheng2001 ***@***.***>
发送时间:2024-03-18 22:34:19 (星期一)
收件人: zsl-whu/csc-mvs ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zsl-whu/csc-mvs] 有关模型端到端训练 (Issue #1)






您好，注意到您的模型使用了两个聚类方法。在整个网络中，您的网络是端到端可训练的嘛？我的理解是，您的聚类方法是无法端到端学习的，所以整个网络也不是端到端的。可以这样理解吗？

**Comment by NanCheng2001** [comment]
ok。我理解啦，感谢！
