### ISSUE TITLE
关于无监督聚类算法的疑问

### ISSUE THREAD

**Issue by NanCheng2001** [zsl-whu/csc-mvs#3]
您好，注意到您的语义分支使用了无监督聚类算法，请问您的深度预测分支对语义分割有促进作用吗？因为从您的论文中看，无监督**语义预测分支似乎并没有可学习的参数**。
  期待您的早日回复。

**Comment by zsl-whu** [comment]
您好，无监督语义分支分别有自己的迭代更新方式，并且二者的权重参数也需要由网络学习。此外，我的目的是深度预测，因此不需要促进语义分割......这些都在论文中有提到。

2024-04-24 10:41:20 "NanCheng2001" ***@***.***> 写道：

您好，注意到您的语义分支使用了无监督聚类算法，请问您的深度预测分支对语义分割有促进作用吗？因为从您的论文中看，无监督语义预测分支似乎并没有可学习的参数。
期待您的早日回复。

**Comment by NanCheng2001** [comment]
感谢！
